In [7]:
""" 导入基本库 """
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

plt.style.use("bmh")
plt.rc('font', family='SimHei', size=13)
pd.set_option('display.max_columns',1000)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth',1000)

In [8]:
""" 导入数据 """
data_path = r'D:\dataset\中国移动消费者人群画像—信用智能评分'

test_data = pd.read_csv(os.path.join(data_path, 'test_dataset.csv'))
train_data = pd.read_csv(os.path.join(data_path, 'train_dataset.csv'))

df_data = pd.concat([train_data, test_data], ignore_index=True)
df_data.head()

     信用分  当月旅游资讯类应用使用次数  当月是否体育场馆消费  当月是否到过福州山姆会员店  当月是否景点游览  当月是否看电影  当月是否逛过福州仓山万达  当月火车类应用使用次数  当月物流快递类应用使用次数  当月网购类应用使用次数  当月视频播放类应用使用次数  当月通话交往圈人数  当月金融理财类应用使用总次数  当月飞机类应用使用次数  是否4G不健康客户  是否大学生客户  是否经常逛商场的人  是否黑名单客户  用户实名制是否通过核实  用户年龄  用户当月账户余额（元）  用户最近一次缴费距今时长（月）                              用户编码  用户网龄（月）  用户话费敏感度  用户账单当月总费用（元）  用户近6个月平均消费值（元）  缴费用户当前是否欠费缴费  缴费用户最近一次缴费金额（元）  近三个月月均商场出现次数
0  664.0             30           1              0         1        0             0            0              0          713           7145         83            2740            0          0        0          1        0            1    44          180                1  a4651f98c82948b186bdcdc8108381b4      186        3        159.20          163.86             0            99.80            75
1  530.0              0           0              0         0        0             0            0              0          414          44862         21            2731            0          1        0          1        0            1    18          110                1  aeb10247db4e4d67b2550bbc42ff9827        5        3        145.10          153.28             0            29.94            16
2  643.0              1           0              0         0        0             0            0              0         3391           4804         59               0            0          0        0          0        0            1    47           70                1  5af23a1e0e77410abb25e9a7eee510aa      145        1        120.20          109.64             0            49.90             1
3  649.0              5           1              0         1        0             0            0              0          500           3141         78            1931            0          0        0          1        0            1    55           90                1  43c64379d3c24a15b8478851b22049e4      234        3        167.42           92.97             0            99.80            26
4  648.0              0           0              0         1        0             0            0              0          522             59         70              64            0          0        0          1        0            1    40           80                1  f1687f3b8a6f4910bd0b13eb634056e2       76        3        101.00           95.47             0            49.90            44

In [9]:

""" 数据属性 """
df_data.info()

print()
print("共有数据集：", df_data.shape[0])
print("共有测试集：", test_data.shape[0])
print("共有训练集：", train_data.shape[0])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 30 columns):
信用分                50000 non-null float64
当月旅游资讯类应用使用次数      100000 non-null int64
当月是否体育场馆消费         100000 non-null int64
当月是否到过福州山姆会员店      100000 non-null int64
当月是否景点游览           100000 non-null int64
当月是否看电影            100000 non-null int64
当月是否逛过福州仓山万达       100000 non-null int64
当月火车类应用使用次数        100000 non-null int64
当月物流快递类应用使用次数      100000 non-null int64
当月网购类应用使用次数        100000 non-null int64
当月视频播放类应用使用次数      100000 non-null int64
当月通话交往圈人数          100000 non-null int64
当月金融理财类应用使用总次数     100000 non-null int64
当月飞机类应用使用次数        100000 non-null int64
是否4G不健康客户          100000 non-null int64
是否大学生客户            100000 non-null int64
是否经常逛商场的人          100000 non-null int64
是否黑名单客户            100000 non-null int64
用户实名制是否通过核实        100000 non-null int64
用户年龄               100000 non-null int64
用户当月账户余额（元）        100000 non-null int64
用户最近一次缴费距今时长（月）    100000 non-null int64
用户编码               100000 non-null object
用户网龄（月）            100000 non-null int64
用户话费敏感度            100000 non-null int64
用户账单当月总费用（元）       100000 non-null float64
用户近6个月平均消费值（元）     100000 non-null float64
缴费用户当前是否欠费缴费       100000 non-null int64
缴费用户最近一次缴费金额（元）    100000 non-null float64
近三个月月均商场出现次数       100000 non-null int64
dtypes: float64(4), int64(25), object(1)
memory usage: 22.9+ MB

共有数据集： 100000
共有测试集： 50000
共有训练集： 50000

In [10]:
""" 数据类别 """
for i,name in enumerate(df_data.columns):
    name_sum = df_data[name].value_counts().shape[0]
    print("{:2}、{:15}      The number of types of features is：{}".format(i + 1, name, name_sum))

 1、信用分                  The number of types of features is：278
 2、当月旅游资讯类应用使用次数        The number of types of features is：934
 3、当月是否体育场馆消费           The number of types of features is：2
 4、当月是否到过福州山姆会员店        The number of types of features is：2
 5、当月是否景点游览             The number of types of features is：2
 6、当月是否看电影              The number of types of features is：2
 7、当月是否逛过福州仓山万达         The number of types of features is：2
 8、当月火车类应用使用次数          The number of types of features is：180
 9、当月物流快递类应用使用次数        The number of types of features is：239
10、当月网购类应用使用次数          The number of types of features is：8382
11、当月视频播放类应用使用次数        The number of types of features is：16067
12、当月通话交往圈人数            The number of types of features is：554
13、当月金融理财类应用使用总次数       The number of types of features is：7232
14、当月飞机类应用使用次数          The number of types of features is：209
15、是否4G不健康客户            The number of types of features is：2
16、是否大学生客户              The number of types of features is：2
17、是否经常逛商场的人            The number of types of features is：2
18、是否黑名单客户              The number of types of features is：2
19、用户实名制是否通过核实          The number of types of features is：2
20、用户年龄                 The number of types of features is：88
21、用户当月账户余额（元）          The number of types of features is：316
22、用户最近一次缴费距今时长（月）      The number of types of features is：2
23、用户编码                 The number of types of features is：100000
24、用户网龄（月）              The number of types of features is：283
25、用户话费敏感度              The number of types of features is：6
26、用户账单当月总费用（元）         The number of types of features is：16597
27、用户近6个月平均消费值（元）       The number of types of features is：22520
28、缴费用户当前是否欠费缴费         The number of types of features is：2
29、缴费用户最近一次缴费金额（元）      The number of types of features is：532
30、近三个月月均商场出现次数         The number of types of features is：93

In [11]:
""" 数据统计 """
df_data.describe()

                信用分  当月旅游资讯类应用使用次数     当月是否体育场馆消费  当月是否到过福州山姆会员店      当月是否景点游览        当月是否看电影   当月是否逛过福州仓山万达    当月火车类应用使用次数  当月物流快递类应用使用次数    当月网购类应用使用次数  当月视频播放类应用使用次数      当月通话交往圈人数  当月金融理财类应用使用总次数    当月飞机类应用使用次数      是否4G不健康客户        是否大学生客户      是否经常逛商场的人        是否黑名单客户    用户实名制是否通过核实           用户年龄    用户当月账户余额（元）  用户最近一次缴费距今时长（月）        用户网龄（月）        用户话费敏感度   用户账单当月总费用（元）  用户近6个月平均消费值（元）   缴费用户当前是否欠费缴费  缴费用户最近一次缴费金额（元）   近三个月月均商场出现次数
count  50000.000000  100000.000000  100000.000000   100000.00000  100000.00000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000   1.000000e+05  100000.000000    100000.00000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000    100000.000000  100000.000000  100000.000000  100000.000000   100000.000000  100000.000000    100000.000000  100000.000000
mean     618.053060      19.394650       0.374730        0.02705       0.47546       0.243800       0.039230       0.564590       1.025860    1161.142610   3.386321e+03      48.211110       975.36609       0.649760       0.088690       0.003620       0.330720       0.048500       0.991240      37.907910     115.684600         0.701420      96.271580       3.352980      99.709021       98.983241       0.051830        53.721932      26.507030
std       42.443022     312.587384       0.484056        0.16223       0.49940       0.429376       0.194143       7.973381      37.482212    4300.092242   1.074417e+04      54.867465      2965.36056      22.299903       0.284297       0.060058       0.470475       0.214821       0.093184      11.625008     448.684984         0.457637      59.112782       1.241129      65.314169       61.002422       0.221685        62.214807      32.739661
min      422.000000       0.000000       0.000000        0.00000       0.00000       0.000000       0.000000       0.000000       0.000000       0.000000   0.000000e+00       1.000000         0.00000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000      10.000000         0.000000       1.000000       0.000000       0.000000        0.000000       0.000000         0.000000       0.000000
25%      594.000000       0.000000       0.000000        0.00000       0.00000       0.000000       0.000000       0.000000       0.000000      18.000000   1.000000e+01      16.000000         6.00000       0.000000       0.000000       0.000000       0.000000       0.000000       1.000000      30.000000      40.000000         0.000000      48.000000       2.000000      53.000000       54.320000       0.000000         0.000000       1.000000
50%      627.000000       0.000000       0.000000        0.00000       0.00000       0.000000       0.000000       0.000000       0.000000     248.000000   3.340000e+02      32.000000       265.00000       0.000000       0.000000       0.000000       0.000000       0.000000       1.000000      36.000000      70.000000         1.000000      94.000000       4.000000      90.000000       89.670000       0.000000        49.900000       8.000000
75%      649.000000       4.000000       1.000000        0.00000       1.00000       0.000000       0.000000       0.000000       0.000000     934.000000   2.440000e+03      62.000000      1145.00000       0.000000       0.000000       0.000000       1.000000       0.000000       1.000000      45.000000     130.000000         1.000000     139.000000       4.000000     134.627500      131.560000       0.000000        99.800000      49.000000
max      719.000000   87681.000000       1.000000        1.00000       1.00000       1.000000       1.000000     775.000000    8235.000000  417536.000000   1.382227e+06    1906.000000    496238.00000    5856.000000       1.000000       1.000000       1.000000       1.000000       1.000000     111.000000  109090.000000         1.000000     288.000000       5.000000    2117.010000     1792.740000       1.000000      1000.000000      92.000000

In [12]:
df_data[df_data['信用分'].isnull()].describe()

       信用分  当月旅游资讯类应用使用次数    当月是否体育场馆消费  当月是否到过福州山姆会员店      当月是否景点游览       当月是否看电影  当月是否逛过福州仓山万达  当月火车类应用使用次数  当月物流快递类应用使用次数   当月网购类应用使用次数  当月视频播放类应用使用次数     当月通话交往圈人数  当月金融理财类应用使用总次数   当月飞机类应用使用次数     是否4G不健康客户       是否大学生客户     是否经常逛商场的人       是否黑名单客户   用户实名制是否通过核实          用户年龄    用户当月账户余额（元）  用户最近一次缴费距今时长（月）       用户网龄（月）       用户话费敏感度  用户账单当月总费用（元）  用户近6个月平均消费值（元）  缴费用户当前是否欠费缴费  缴费用户最近一次缴费金额（元）  近三个月月均商场出现次数
count  0.0   50000.000000  50000.000000   50000.000000  50000.000000  50000.000000  50000.000000  50000.00000   50000.000000   50000.00000    50000.00000  50000.000000    50000.000000  50000.000000  50000.000000  50000.000000  50000.000000  50000.000000  50000.000000  50000.000000   50000.000000     50000.000000  50000.000000  50000.000000  50000.000000    50000.000000  50000.000000     50000.000000  50000.000000
mean   NaN      19.672180      0.375340       0.026980      0.476500      0.245320      0.039760      0.57584       0.853880    1173.46996     3406.12244     48.367720      979.229100      0.595100      0.088800      0.003520      0.331940      0.048200      0.992260     37.932380     117.196800         0.702740     96.094480      3.354040     99.842912       99.234402      0.051120        54.027936     26.441540
std    NaN     408.041808      0.484215       0.162027      0.499452      0.430281      0.195397      8.20404      28.848873    4586.71334     9919.40536     55.518686     2924.008879     13.025441      0.284458      0.059226      0.470914      0.214191      0.087637     11.636829     556.938946         0.457057     59.048962      1.241067     65.301379       61.245686      0.220245        62.614124     32.690192
min    NaN       0.000000      0.000000       0.000000      0.000000      0.000000      0.000000      0.00000       0.000000       0.00000        0.00000      1.000000        0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      10.000000         0.000000      1.000000      0.000000      0.000000        0.000000      0.000000         0.000000      0.000000
25%    NaN       0.000000      0.000000       0.000000      0.000000      0.000000      0.000000      0.00000       0.000000      17.00000       10.00000     16.000000        5.000000      0.000000      0.000000      0.000000      0.000000      0.000000      1.000000     30.000000      40.000000         0.000000     48.000000      2.000000     53.200000       54.450000      0.000000         0.000000      1.000000
50%    NaN       0.000000      0.000000       0.000000      0.000000      0.000000      0.000000      0.00000       0.000000     246.00000      333.00000     32.000000      263.000000      0.000000      0.000000      0.000000      0.000000      0.000000      1.000000     36.000000      70.000000         1.000000     94.000000      4.000000     90.000000       90.000000      0.000000        49.900000      8.000000
75%    NaN       4.000000      1.000000       0.000000      1.000000      0.000000      0.000000      0.00000       0.000000     935.00000     2455.00000     62.000000     1144.000000      0.000000      0.000000      0.000000      1.000000      0.000000      1.000000     45.000000     130.000000         1.000000    139.000000      4.000000    135.235000      132.000000      0.000000        99.800000     49.000000
max    NaN   87681.000000      1.000000       1.000000      1.000000      1.000000      1.000000    775.00000    5462.000000  417536.00000   295210.00000   1633.000000   329767.000000   1645.000000      1.000000      1.000000      1.000000      1.000000      1.000000    108.000000  109090.000000         1.000000    288.000000      5.000000   2117.010000     1792.740000      1.000000      1000.000000     92.000000

In [13]:
df_data[df_data['信用分'].notnull()].describe()

                信用分  当月旅游资讯类应用使用次数   当月是否体育场馆消费  当月是否到过福州山姆会员店     当月是否景点游览       当月是否看电影  当月是否逛过福州仓山万达   当月火车类应用使用次数  当月物流快递类应用使用次数    当月网购类应用使用次数  当月视频播放类应用使用次数     当月通话交往圈人数  当月金融理财类应用使用总次数   当月飞机类应用使用次数     是否4G不健康客户       是否大学生客户     是否经常逛商场的人       是否黑名单客户  用户实名制是否通过核实          用户年龄   用户当月账户余额（元）  用户最近一次缴费距今时长（月）       用户网龄（月）       用户话费敏感度  用户账单当月总费用（元）  用户近6个月平均消费值（元）  缴费用户当前是否欠费缴费  缴费用户最近一次缴费金额（元）  近三个月月均商场出现次数
count  50000.000000   50000.000000  50000.00000   50000.000000  50000.00000  50000.000000  50000.000000  50000.000000   50000.000000   50000.000000   5.000000e+04  50000.000000     50000.00000  50000.000000  50000.000000  50000.000000  50000.000000  50000.000000  50000.00000  50000.000000  50000.000000     50000.000000  50000.000000  50000.000000  50000.000000    50000.000000  50000.000000     50000.000000  50000.000000
mean     618.053060      19.117120      0.37412       0.027120      0.47442      0.242280      0.038700      0.553340       1.197840    1148.815260   3.366519e+03     48.054500       971.50308      0.704420      0.088580      0.003720      0.329500      0.048800      0.99022     37.883440    114.172400         0.700100     96.448680      3.351920     99.575130       98.732081      0.052540        53.415929     26.572520
std       42.443022     170.074772      0.48390       0.162435      0.49935      0.428467      0.192881      7.735913      44.469584    3992.957952   1.151006e+04     54.208524      3006.16776     28.721302      0.284139      0.060879      0.470036      0.215452      0.09841     11.613239    304.063961         0.458218     59.176593      1.241202     65.327335       60.757758      0.223116        61.812022     32.789251
min      422.000000       0.000000      0.00000       0.000000      0.00000      0.000000      0.000000      0.000000       0.000000       0.000000   0.000000e+00      1.000000         0.00000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000     10.000000         0.000000      1.000000      0.000000      0.000000        0.000000      0.000000         0.000000      0.000000
25%      594.000000       0.000000      0.00000       0.000000      0.00000      0.000000      0.000000      0.000000       0.000000      18.000000   1.000000e+01     16.000000         6.00000      0.000000      0.000000      0.000000      0.000000      0.000000      1.00000     30.000000     40.000000         0.000000     48.000000      2.000000     52.675000       54.180000      0.000000         0.000000      1.000000
50%      627.000000       0.000000      0.00000       0.000000      0.00000      0.000000      0.000000      0.000000       0.000000     250.000000   3.350000e+02     32.000000       267.00000      0.000000      0.000000      0.000000      0.000000      0.000000      1.00000     36.000000     70.000000         1.000000     94.000000      4.000000     89.620000       89.320000      0.000000        49.900000      8.000000
75%      649.000000       4.000000      1.00000       0.000000      1.00000      0.000000      0.000000      0.000000       0.000000     932.000000   2.423250e+03     61.000000      1147.25000      0.000000      0.000000      0.000000      1.000000      0.000000      1.00000     45.000000    130.000000         1.000000    139.000000      4.000000    133.945000      131.160000      0.000000        99.800000     50.000000
max      719.000000   13965.000000      1.00000       1.000000      1.00000      1.000000      1.000000    474.000000    8235.000000  234336.000000   1.382227e+06   1906.000000    496238.00000   5856.000000      1.000000      1.000000      1.000000      1.000000      1.00000    111.000000  49040.000000         1.000000    288.000000      5.000000   1164.290000      840.570000      1.000000       998.000000     92.000000